PUT http://localhost:3003/api/blogs/609a6c1da1e3f815103130c4
Content-Type: application/json

{
    "title": "Kuinka muutetaan blogi",
    "author":"Olli Kirjoittaja",
    "url": "www.wordpress.com",
    "likes":7
}