PUT http://localhost:3003/api/blogs/609a650b848f0b4278db89c2
Content-Type: application/json

{
    "title": "Kuinka muutetaan blogi",
    "author":"Olli Kirjoittaja",
    "url": "www.wordpress.com",
    "likes":7
}